### ISSUE TITLE
Error while loading plugin in Domoticz (Raspberry Pi)

### ISSUE THREAD

**Issue by evanhemmen** [superjunky/Domoticz-Brel-Plugin#10] opened 2023-06-14 15:24 UTC
Hi, thanks for this plugin, I;m struggling to get it working in my situation. I followed all the steps in your guide. 

Now when I go to the hardware page in Domoticz I don't see the plugin. After visiting the hardware page I see the following error in my log:

`
2023-06-14 17:16:53.993 Error: PluginList: Parsing '/home/pi/domoticz/plugins/Domoticz-Brel-Plugin/', 'Error reading end tag.' at line 18 column 9 in XML '<plugin key="Brel-Home-Hub" name="Brel Home Hub" author="Superjunky" version="1.0.0" wikilink="https://github.com/superjunky/Domoticz-Brel-Plugin" externallink="https://www.brel-motors.nl/brel-app.html">`

Any suggestions would be appreciated.

**Comment by tbryel** [comment] 2023-08-26 07:07
Same issue for myself, looked at the plugins but don't see anything strange in the plugins on line 18:
`plugin.py line 18:        <h3>Features</h3>`
`brel.py line 18: 			self.s.settimeout(5)`

The error also refers to an .xml, i'm not able to find any .xml as part of the plugin. Maybe the error refers to the url https://www.brel-motors.nl/brel-app.html which isn't working when I directly call it but I'm not sure that's the cause as it's an .html and not an .xml

**Comment by hansa031** [comment] 2023-10-04 13:10
Hi Robbie,

I have the same issue and I'm using domoticz 2023.2. I understood you are not using the Brel-hub anymore and maybe this is stopping you from maintaining this plugin. This is a pity because it's used by many to great satisfaction. If you are willing to fix this error I'm more than willing to test it! ;)

Cheers,
Hans

**Comment by casio1983** [comment] 2023-11-19 11:51
Hi,

Same issue but this can be easily fixed by adding a missing \</li> as indicated by the error in Domoticz in plugin.py on line 28.
Note that the comment is not included to the offset :)

```diff
diff --git a/plugin.py b/plugin.py
index 8466be7..9b435f3 100644
--- a/plugin.py
+++ b/plugin.py
@@ -28,7 +28,7 @@
                <li>Enter the KEY of your Brel Home Hub. Get the KEY by quickly tapping 5 times on "Version 1.x.x(x)" in your Brel SmartPhone app. You'll get the 16-byte KEY in a popup, which you can then copy/paste. On Android tap next to the profile picture instead of the version-number.</li>
                <li>Don't forget to let Domoticz allow new devices before you activate this plugin!</li>
                <li>Optionally you can specify default positions and/or angle's for your blinds' Open and Close buttons. Similar to a Favorite position. Read on for learning more about this.</li>
-               <li>If you have trouble loading your pycrypto module, you can manually add an accessToken in your settings. Get it by generating it at https://www.devglan.com/online-tools/aes-encryption-decryption
+               <li>If you have trouble loading your pycrypto module, you can manually add an accessToken in your settings. Get it by generating it at https://www.devglan.com/online-tools/aes-encryption-decryption</li>
                </ul>
         <h3>The "Defaults array" explained</h3>
                Let's start with an example array:<br /><br />
```

BR Cas

**Comment by superjunky** [comment] 2023-11-19 16:41
Great, the fix is added!

**Closed as completed by superjunky** 2023-11-19 16:41 UTC
